// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcmigsqzvfkukqzusudg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbWlnc3F6dmZrdWtxenVzdWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTMwNjksImV4cCI6MjA1ODc2OTA2OX0.Zj6RF2fCYd_3239hyd-jOjgZXk70nMXpv6Kwt0V7jJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);